Repositorio con simulaciones de diferentes situaciones radar: deteccion de pulsos cortos rectangulares (con matched filters), radar pulsado con chirp, diagrama Doppler, Tracking con Filtro de Kalman, etc... 
Después se pasa a ejemplos de Antenas y Phased Array, así como procesado de señal radar y radares FMCW.
